# Deploy IEF Policies
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# specific path build
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - policies
    exclude:
    - docs/README.md

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 
      |
      Install-Module -Name IefPolicies -Scope CurrentUser -Force -AllowPrerelease
      Connect-IefPolicies -tenant ${env:TENANTNAME} -clientId ${env:CLIENTID} -clientSecret ${env:CLIENT_SECRET}
      Import-IefPolicies -sourceDirectory "./policies" -configurationFilePath "./policies/conf.json"
      
  env:
    CLIENT_SECRET: $(clientSecret)

