# Deploy IEF Policies
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Install-Module -Name IefPolicies -Scope CurrentUser -Force'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Connect-IefPolicies -tenantId ${env:TENANTID} -clientId ${env:CLIENTID} -clientSecret ${env:CLIENT_SECRET}'
  env:
    CLIENT_SECRET: $(clientSecret)

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Import-IefPolicies -sourceDirectories "./policies" -configurationFilePath "./policies/conf.json"'
